services:
  php-apache:
    build:
      context: .
      dockerfile: docker/php-apache/Dockerfile
    ports:
      - 80:80
    volumes:
    - .:/var/www/html/
    depends_on:
      - db
#  db:
#    image: mysql:8
#    environment:
#      MYSQL_ROOT_PASSWORD: 1234
#      MYSQL_DATABASE: uavoice
#    volumes:
#      - mysql-data:/var/lib/mysql

  db:
    image: mariadb:11.8
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=washinwar
      - MARIADB_USER=washinwar
      - MARIADB_PASSWORD=washinwar
      - MARIADB_RANDOM_ROOT_PASSWORD=1
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db-data: